### ISSUE TITLE
pipeline update 9.1.23

### ISSUE THREAD

**Issue by othmya** [social-link-analytics-group-bsc/biohackathon-2022-project-24#4]
# Pipeline update

I have updated some parts of the pipeline, so as to have a provisional small dataset on which we can start testing different hypotheses with the plots (@beatrizurda, @vicruiser). The dataset is attached in this issue (here: [CS_def.csv](https://github.com/social-link-analytics-group-bsc/biohackathon-2022-project-24/files/10372875/CS_def.csv)) , and also in the updated repo, it is called `CS_def.csv`. Note that only a small fraction (about 25%) of PMCIDs actually have male and female counts. If these are too low, we can provide a bigger set of sentences with the actual NLP model (e.g. 10.000 sentences?).

> NOTE: I have pushed the code to a new branch, `pipeline_v2`, as I was afraid of deleting anything on the main branch. We can merge afterwards.

## Additions

- I have included a script, `convert_NLP_to_df.py` that converst the `json` result from the NLP model to a readable `pandas` dataframe. (It would be best if merged with the `get_sex_bias.py` script)
- `more_filtering.py` is now **parallelized**, and adds more information to each PMCID: institution, funding source, country, awards (if the paper has received any), the ISSN (for faster localization of relevant publications), along with the type of article. Regarding the article type, it could be beneficial to have different types of articles (research-papers, or reviews) for the downstream analysis.
- `country_tagger.py`: It completes information regarding institutions and country of origin.
- `get_IF_journal.py`: Adds the IF for each journal. There is also the possibility to include the average IF of the last 5 years, if we think it would be more representative of the "growth" of a given journal. 
- `gender_guess.py`: Adds the gender of the first and last author. This is done by checking both the first and last names of each of them. We can discuss how to tackle weird scenarios (e.g. first name male, last name female). It has been also parallelized.

## TODO:
- `add_metadata.py`: I don't know why, but I keep obtaining the same MESH terms for all different PMCIDs. I have parallelized the function, but I don't know if this can affect the MESH terms it retrieves.
- Retrain the model with the % of male and female, so @BlancaCalvo can re-run it with the full set of sentences.
- There is the possibility of adding the citations from each paper. This could be also interesting to include, as some papers discussing biases on literature focus on number of male and female citations.
- Create a set of 1000 sentences in order to create a web-app interface with Prodigy -- @BlancaCalvo

**Comment by Oliph** [comment]
Did you upload it somewhere?

**Comment by othmya** [comment]
It should be embedded in the issue above, and in the branch `pipeline_v2`. I didn't want to push to main, as we can merge afterwards.

**Comment by BlancaCalvo** [comment]
Hi, the 1000 sentences, where do I extract them from? should I process random articles from the 400k? Or should you provide them to me?

**Comment by othmya** [comment]
Yes! I will provide them to you in a .csv format, with their respective PMCID, as soon as possible.

**Comment by othmya** [comment]
> Hi, the 1000 sentences, where do I extract them from? should I process random articles from the 400k? Or should you provide them to me?

@BlancaCalvo You have 1422 sentences in this file: 
[sentences_for_retraining.csv](https://github.com/social-link-analytics-group-bsc/biohackathon-2022-project-24/files/10402031/sentences_for_retraining.csv), hope this works.
